CREATE TABLE NEGOCIACAO_ITEM (
    ID_NEGOCIACAO INTEGER NOT NULL,
    SEQUENCIA INTEGER NOT NULL,
    QUANTIDADE INTEGER,
    VALOR_UNITARIO  DECIMAL(18,2),
    VALOR_TOTAL  DECIMAL(18,2),
    ID_PRODUTO INTEGER);

ALTER TABLE NEGOCIACAO_ITEM
ADD CONSTRAINT PK_NEGOCIACAO_ITEM
PRIMARY KEY (ID_NEGOCIACAO,SEQUENCIA);

ALTER TABLE NEGOCIACAO_ITEM
ADD CONSTRAINT FK_NEGOCIACAO_ITEM_001
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTO(ID);

ALTER TABLE NEGOCIACAO_ITEM
ADD CONSTRAINT FK_NEGOCIACAO_ITEM_002
FOREIGN KEY (ID_NEGOCIACAO)
REFERENCES NEGOCIACAO(ID);

