CREATE TABLE NEGOCIACAO (
    ID INTEGER NOT NULL,
    ID_PRODUTOR INTEGER,
    ID_DISTRIBUIDOR INTEGER,
    STATUS VARCHAR(30),
    VALOR DECIMAL(18,2),
    DATA DATE,
	DATASTATUS DATE);

ALTER TABLE NEGOCIACAO
ADD CONSTRAINT PK_NEGOCIACAO
PRIMARY KEY (ID);

CREATE SEQUENCE NEGOCIACAO_ID;

ALTER SEQUENCE NEGOCIACAO_ID RESTART WITH 1;

ALTER TABLE NEGOCIACAO
ADD CONSTRAINT FK_NEGOCIACAO_001
FOREIGN KEY (ID_PRODUTOR)
REFERENCES PRODUTOR(ID);

ALTER TABLE NEGOCIACAO
ADD CONSTRAINT FK_NEGOCIACAO_002
FOREIGN KEY (ID_DISTRIBUIDOR)
REFERENCES DISTRIBUIDOR(ID);

ALTER TABLE NEGOCIACAO
ADD CONSTRAINT CHK_NEGOCIACAO_001
CHECK (STATUS = 'Pendente' or STATUS = 'Aprovada' or STATUS = 'Concluir' or STATUS = 'Cancelada');