CREATE TABLE PRODUTO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(255),
    VALOR DECIMAL(18,2));

ALTER TABLE PRODUTO
ADD CONSTRAINT PK_PRODUTO
PRIMARY KEY (ID);

CREATE SEQUENCE PRODUTO_ID;

ALTER SEQUENCE PRODUTO_ID RESTART WITH 1;

