CREATE TABLE PRODUTOR_CREDITO (
    ID INTEGER NOT NULL,
    ID_PRODUTOR INTEGER NOT NULL,
    ID_DISTRIBUIDOR INTEGER,
    VALOR DECIMAL(18,2));

ALTER TABLE PRODUTOR_CREDITO
ADD CONSTRAINT PK_PRODUTOR_CREDITO
PRIMARY KEY (ID,ID_PRODUTOR);

CREATE SEQUENCE PRODUTOR_CREDITO_ID;

ALTER SEQUENCE PRODUTOR_CREDITO_ID RESTART WITH 1;

ALTER TABLE PRODUTOR_CREDITO
ADD CONSTRAINT FK_PRODUTOR_CREDITO_001
FOREIGN KEY (ID_PRODUTOR)
REFERENCES PRODUTOR(ID);

ALTER TABLE PRODUTOR_CREDITO
ADD CONSTRAINT FK_PRODUTOR_CREDITO_002
FOREIGN KEY (ID_DISTRIBUIDOR)
REFERENCES DISTRIBUIDOR(ID);


